# -*- coding: utf-8 -*-
"""Simple_CNN_parameter_0.3M(Baseline)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IJ_3NnVNda_Tgdy88N40ddtBU_4E5NYe

https://github.com/sethuram-21/Mixed-Type-Wafer-Defect-Classification/blob/main/Attention-Augmented-CNN.ipynb
"""

import torch
!pip install split-folders

import splitfolders

input = "data"
output = "data split"

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
data = np.load('/content/drive/MyDrive/dataset/Wafer_Map_Datasets.npz')
print(data.files)  # 파일 내 저장된 모든 배열명 리스트 출력

import numpy as np
data = np.load('/content/drive/MyDrive/dataset/Wafer_Map_Datasets.npz')

# 내부 키 확인
print(data.files)  # ['arr_0', 'arr_1']

# 배열 불러오기
images = data['arr_0']
labels = data['arr_1']

import numpy as np
from PIL import Image
import os

data = np.load('/content/drive/MyDrive/dataset/Wafer_Map_Datasets.npz')
images = data['arr_0']   # (num_samples, H, W) or (num_samples, H, W, C)
labels = data['arr_1']   # (num_samples,)

for i, (img, label) in enumerate(zip(images, labels)):
    out_dir = f'data/class{label}'
    os.makedirs(out_dir, exist_ok=True)
    Image.fromarray(img).save(f'{out_dir}/{i}.png')

splitfolders.ratio(input, output=output, seed=1337, ratio=(0.72,0.08,0.2))

import os
import torch
import torchvision
import torchvision.transforms as transforms

os.listdir('./data split/train')

training_dataset_path="./data split/train"

training_transforms = transforms.Compose([transforms.Resize((52,52)), transforms.ToTensor()])

train_dataset = torchvision.datasets.ImageFolder( root = training_dataset_path, transform = training_transforms)

train_loader = torch.utils.data.DataLoader( dataset = train_dataset, batch_size = 32 , shuffle=False)

def get_mean_std(loader):
    # Compute the mean and standard deviation of all pixels in the dataset
    num_pixels = 0
    mean = 0.0
    std = 0.0
    for images, _ in loader:
        batch_size, num_channels, height, width = images.shape
        num_pixels += batch_size * height * width
        mean += images.mean(axis=(0, 2, 3)).sum()
        std += images.std(axis=(0, 2, 3)).sum()

    mean /= num_pixels
    std /= num_pixels

    return mean, std

mean,std = get_mean_std(train_loader)

import matplotlib.pyplot as plt
import numpy as np

train_dataset_path = './data split/train'
test_dataset_path = './data split/test'
val_dataset_path = './data split/val'

train_transforms = transforms.Compose([
    transforms.Resize((52,52)),
    transforms.Grayscale(num_output_channels=1),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
    transforms.Normalize(torch.Tensor(mean), torch.Tensor(std))
])

test_transforms = transforms.Compose([
    transforms.Resize((52,52)),
    transforms.Grayscale(num_output_channels=1),
    transforms.ToTensor(),
    transforms.Normalize(torch.Tensor(mean), torch.Tensor(std))
])

val_transforms = transforms.Compose([
    transforms.Resize((52,52)),
    transforms.Grayscale(num_output_channels=1),
    transforms.ToTensor(),
    transforms.Normalize(torch.Tensor(mean), torch.Tensor(std))
])

train_dataset = torchvision.datasets.ImageFolder(root = train_dataset_path, transform = train_transforms)
test_dataset = torchvision.datasets.ImageFolder(root = test_dataset_path, transform = test_transforms)
val_dataset = torchvision.datasets.ImageFolder(root = val_dataset_path, transform = val_transforms)

train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = torch.utils.data.DataLoader(test_dataset, batch_size=32, shuffle=False)
val_loader = torch.utils.data.DataLoader(val_dataset, batch_size=32, shuffle=False)

def set_device():
    if torch.cuda.is_available():
        dev = "cuda"
    else :
        dev = "cpu"
    return torch.device(dev)

"""0.37m layer 수정"""

# -*- coding: utf-8 -*-
"""
Simple CNN Baseline for MixedWM38 (Working Version)
성공한 모델의 전처리 방식 그대로 사용 + 단순한 CNN
Target: 95% (파라미터 수: ~0.5M)
"""

import os
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
from torch.utils.data import DataLoader
import numpy as np
from tqdm import tqdm

# ============================================
class SimpleCNN(nn.Module):
    """
    약 0.30M 파라미터 CNN (정확히 ~0.31M)
    """
    def __init__(self, num_classes=38):
        super().__init__()

        self.features = nn.Sequential(
            nn.Conv2d(1, 64, 3, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2, 2),  # 52 -> 26

            nn.Conv2d(64, 128, 3, padding=1),
            nn.BatchNorm2d(128),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2, 2),  # 26 -> 13

            nn.Conv2d(128, 160, 3, padding=1),  # 192 → 160으로 감소
            nn.BatchNorm2d(160),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2, 2),  # 13 -> 6
        )

        self.classifier = nn.Sequential(
            nn.AdaptiveAvgPool2d((1, 1)),
            nn.Flatten(),
            nn.Linear(160, 256),  # 160 → 256
            nn.ReLU(inplace=True),
            nn.Dropout(0.5),
            nn.Linear(256, num_classes)
        )

    def forward(self, x):
        x = self.features(x)
        x = self.classifier(x)
        return x




# 2. Early Stopping
# ============================================
class EarlyStopping:
    def __init__(self, patience=7, min_delta=0.001, verbose=True):
        self.patience = patience
        self.min_delta = min_delta
        self.verbose = verbose
        self.counter = 0
        self.best_score = None
        self.early_stop = False
        self.val_loss_min = float('inf')

    def __call__(self, val_loss, model, path):
        score = -val_loss
        if self.best_score is None:
            self.best_score = score
            self.save_checkpoint(val_loss, model, path)
        elif score < self.best_score + self.min_delta:
            self.counter += 1
            if self.verbose:
                print(f'EarlyStopping counter: {self.counter}/{self.patience}')
            if self.counter >= self.patience:
                self.early_stop = True
        else:
            self.best_score = score
            self.save_checkpoint(val_loss, model, path)
            self.counter = 0

    def save_checkpoint(self, val_loss, model, path):
        if self.verbose:
            print(f'Validation loss decreased ({self.val_loss_min:.6f} -> {val_loss:.6f}). Saving...')
        torch.save(model.state_dict(), path)
        self.val_loss_min = val_loss


# ============================================
# 3. Mean/Std 계산 함수 (성공한 모델과 동일)
# ============================================
def get_mean_std(loader):
    """데이터셋의 mean, std 계산"""
    num_pixels = 0
    mean = 0.0
    std = 0.0
    for images, _ in loader:
        batch_size, num_channels, height, width = images.shape
        num_pixels += batch_size * height * width
        mean += images.mean(axis=(0, 2, 3)).sum()
        std += images.std(axis=(0, 2, 3)).sum()

    mean /= num_pixels
    std /= num_pixels

    return mean, std


# ============================================
# 4. Training Functions
# ============================================
def train_epoch(model, loader, criterion, optimizer, device):
    model.train()
    running_loss = 0.0
    correct = 0
    total = 0

    for inputs, targets in loader:
        inputs, targets = inputs.to(device), targets.to(device)

        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, targets)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()
        _, predicted = outputs.max(1)
        total += targets.size(0)
        correct += predicted.eq(targets).sum().item()

    return running_loss / len(loader), 100. * correct / total


def validate(model, loader, criterion, device):
    model.eval()
    running_loss = 0.0
    correct = 0
    total = 0

    with torch.no_grad():
        for inputs, targets in loader:
            inputs, targets = inputs.to(device), targets.to(device)
            outputs = model(inputs)
            loss = criterion(outputs, targets)

            running_loss += loss.item()
            _, predicted = outputs.max(1)
            total += targets.size(0)
            correct += predicted.eq(targets).sum().item()

    return running_loss / len(loader), 100. * correct / total


# ============================================
# 5. Main Training
# ============================================
def main():
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f'Device: {device}\n')

    # Paths
    train_path = './data split/train'
    val_path = './data split/val'
    test_path = './data split/test'

    print("="*60)
    print("Step 1: Mean/Std 계산")
    print("="*60)

    # Mean/Std 계산을 위한 임시 로더
    temp_transforms = transforms.Compose([
        transforms.Resize((52, 52)),
        transforms.Grayscale(num_output_channels=1),
        transforms.ToTensor()
    ])

    temp_dataset = torchvision.datasets.ImageFolder(train_path, transform=temp_transforms)
    temp_loader = DataLoader(temp_dataset, batch_size=32, shuffle=False)

    mean, std = get_mean_std(temp_loader)
    print(f"Calculated Mean: {mean:.4f}")
    print(f"Calculated Std: {std:.4f}\n")

    # 실제 학습용 Transforms (성공한 모델과 동일)
    print("="*60)
    print("Step 2: 데이터 로딩")
    print("="*60)

    train_transforms = transforms.Compose([
        transforms.Resize((52, 52)),
        transforms.Grayscale(num_output_channels=1),
        transforms.RandomHorizontalFlip(),
        transforms.ToTensor(),
        transforms.Normalize([mean], [std])
    ])

    test_val_transforms = transforms.Compose([
        transforms.Resize((52, 52)),
        transforms.Grayscale(num_output_channels=1),
        transforms.ToTensor(),
        transforms.Normalize([mean], [std])
    ])

    # Datasets
    train_dataset = torchvision.datasets.ImageFolder(train_path, transform=train_transforms)
    val_dataset = torchvision.datasets.ImageFolder(val_path, transform=test_val_transforms)
    test_dataset = torchvision.datasets.ImageFolder(test_path, transform=test_val_transforms)

    # Loaders
    train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=32, shuffle=False)
    test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

    print(f"Train samples: {len(train_dataset)}")
    print(f"Val samples: {len(val_dataset)}")
    print(f"Test samples: {len(test_dataset)}")
    print(f"Number of classes: {len(train_dataset.classes)}\n")

    # Model
    print("="*60)
    print("Step 3: 모델 생성")
    print("="*60)

    num_classes = len(train_dataset.classes)
    model = SimpleCNN(num_classes=num_classes).to(device)

    total_params = sum(p.numel() for p in model.parameters())
    print(f"Total parameters: {total_params:,}")
    print(f"Model size: {total_params / 1e6:.2f}M\n")

    # Loss & Optimizer (성공한 모델과 유사하게)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=0.001)
    scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=7, gamma=0.1)

    # Early Stopping
    early_stopping = EarlyStopping(patience=7, verbose=True)

    # Training
    print("="*60)
    print("Step 4: 학습 시작")
    print("="*60)

    num_epochs = 50
    best_val_acc = 0.0

    for epoch in range(num_epochs):
        print(f"\nEpoch {epoch+1}/{num_epochs}")
        print("-" * 60)

        # Train
        train_loss, train_acc = train_epoch(model, train_loader, criterion, optimizer, device)

        # Validate
        val_loss, val_acc = validate(model, val_loader, criterion, device)

        # Scheduler
        scheduler.step()

        # Save best
        if val_acc > best_val_acc:
            best_val_acc = val_acc
            torch.save(model.state_dict(), 'best_simple_cnn.pth')

        # Print
        print(f'Train Loss: {train_loss:.4f} | Train Acc: {train_acc:.2f}%')
        print(f'Val Loss: {val_loss:.4f} | Val Acc: {val_acc:.2f}%')
        print(f'Best Val Acc: {best_val_acc:.2f}%')

        # Early Stopping
        early_stopping(val_loss, model, 'early_stop_checkpoint.pth')
        if early_stopping.early_stop:
            print(f"\nEarly Stopping at Epoch {epoch+1}")
            break

    # Test
    print("\n" + "="*60)
    print("Step 5: 최종 테스트")
    print("="*60)

    model.load_state_dict(torch.load('best_simple_cnn.pth'))
    test_loss, test_acc = validate(model, test_loader, criterion, device)

    print(f"\n최종 결과:")
    print(f"Test Accuracy: {test_acc:.2f}%")
    print(f"Best Val Accuracy: {best_val_acc:.2f}%")
    print(f"Total Parameters: {total_params:,} ({total_params/1e6:.2f}M)")
    print(f"\n학습 완료! ✅")


if __name__ == '__main__':
    main()

"""mean std 수정"""

# -*- coding: utf-8 -*-
"""
Simple CNN Baseline for MixedWM38 (Working Version)
성공한 모델의 전처리 방식 그대로 사용 + 단순한 CNN
Target: 95% (파라미터 수: ~0.5M)
"""

import os
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
from torch.utils.data import DataLoader
import numpy as np
from tqdm import tqdm

# ============================================
class SimpleCNN(nn.Module):
    def __init__(self, num_classes=38):
        super().__init__()

        self.features = nn.Sequential(
            nn.Conv2d(1, 64, 3, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2, 2),  # 52 -> 26

            nn.Conv2d(64, 128, 3, padding=1),
            nn.BatchNorm2d(128),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2, 2),  # 26 -> 13

            nn.Conv2d(128, 160, 3, padding=1),  # 192 → 160으로 감소
            nn.BatchNorm2d(160),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2, 2),  # 13 -> 6
        )

        self.classifier = nn.Sequential(
            nn.AdaptiveAvgPool2d((1, 1)),
            nn.Flatten(),
            nn.Linear(160, 256),  # 160 → 256
            nn.ReLU(inplace=True),
            nn.Dropout(0.5),
            nn.Linear(256, num_classes)
        )

    def forward(self, x):
        x = self.features(x)
        x = self.classifier(x)
        return x




# 2. Early Stopping
# ============================================
class EarlyStopping:
    def __init__(self, patience=7, min_delta=0.001, verbose=True):
        self.patience = patience
        self.min_delta = min_delta
        self.verbose = verbose
        self.counter = 0
        self.best_score = None
        self.early_stop = False
        self.val_loss_min = float('inf')

    def __call__(self, val_loss, model, path):
        score = -val_loss
        if self.best_score is None:
            self.best_score = score
            self.save_checkpoint(val_loss, model, path)
        elif score < self.best_score + self.min_delta:
            self.counter += 1
            if self.verbose:
                print(f'EarlyStopping counter: {self.counter}/{self.patience}')
            if self.counter >= self.patience:
                self.early_stop = True
        else:
            self.best_score = score
            self.save_checkpoint(val_loss, model, path)
            self.counter = 0

    def save_checkpoint(self, val_loss, model, path):
        if self.verbose:
            print(f'Validation loss decreased ({self.val_loss_min:.6f} -> {val_loss:.6f}). Saving...')
        torch.save(model.state_dict(), path)
        self.val_loss_min = val_loss


# ============================================
# 3. Mean/Std 계산 함수 (성공한 모델과 동일)
# ============================================
def get_mean_std(loader):
    mean = 0.0
    std = 0.0
    total_images = 0

    for images, _ in loader:
        images = images.view(images.size(0), -1)
        mean += images.mean(1).sum()
        std += images.std(1).sum()
        total_images += images.size(0)

    mean /= total_images
    std /= total_images
    return mean.item(), std.item()


# ============================================
# 4. Training Functions
# ============================================
def train_epoch(model, loader, criterion, optimizer, device):
    model.train()
    running_loss = 0.0
    correct = 0
    total = 0

    for inputs, targets in loader:
        inputs, targets = inputs.to(device), targets.to(device)

        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, targets)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()
        _, predicted = outputs.max(1)
        total += targets.size(0)
        correct += predicted.eq(targets).sum().item()

    return running_loss / len(loader), 100. * correct / total


def validate(model, loader, criterion, device):
    model.eval()
    running_loss = 0.0
    correct = 0
    total = 0

    with torch.no_grad():
        for inputs, targets in loader:
            inputs, targets = inputs.to(device), targets.to(device)
            outputs = model(inputs)
            loss = criterion(outputs, targets)

            running_loss += loss.item()
            _, predicted = outputs.max(1)
            total += targets.size(0)
            correct += predicted.eq(targets).sum().item()

    return running_loss / len(loader), 100. * correct / total


# ============================================
# 5. Main Training
# ============================================
def main():
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f'Device: {device}\n')

    # Paths
    train_path = './data split/train'
    val_path = './data split/val'
    test_path = './data split/test'

    print("="*60)
    print("Step 1: Mean/Std 계산")
    print("="*60)

    # Mean/Std 계산을 위한 임시 로더
    temp_transforms = transforms.Compose([
        transforms.Resize((52, 52)),
        transforms.Grayscale(num_output_channels=1),
        transforms.ToTensor()
    ])

    temp_dataset = torchvision.datasets.ImageFolder(train_path, transform=temp_transforms)
    temp_loader = DataLoader(temp_dataset, batch_size=32, shuffle=False)

    mean, std = get_mean_std(temp_loader)
    print(f"Calculated Mean: {mean:.4f}")
    print(f"Calculated Std: {std:.4f}\n")

    # 실제 학습용 Transforms (성공한 모델과 동일)
    print("="*60)
    print("Step 2: 데이터 로딩")
    print("="*60)

    train_transforms = transforms.Compose([
        transforms.Resize((52, 52)),
        transforms.Grayscale(num_output_channels=1),
        transforms.RandomHorizontalFlip(),
        transforms.ToTensor(),
        transforms.Normalize([mean], [std])
    ])

    test_val_transforms = transforms.Compose([
        transforms.Resize((52, 52)),
        transforms.Grayscale(num_output_channels=1),
        transforms.ToTensor(),
        transforms.Normalize([mean], [std])
    ])

    # Datasets
    train_dataset = torchvision.datasets.ImageFolder(train_path, transform=train_transforms)
    val_dataset = torchvision.datasets.ImageFolder(val_path, transform=test_val_transforms)
    test_dataset = torchvision.datasets.ImageFolder(test_path, transform=test_val_transforms)

    # Loaders
    train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=32, shuffle=False)
    test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

    print(f"Train samples: {len(train_dataset)}")
    print(f"Val samples: {len(val_dataset)}")
    print(f"Test samples: {len(test_dataset)}")
    print(f"Number of classes: {len(train_dataset.classes)}\n")

    # Model
    print("="*60)
    print("Step 3: 모델 생성")
    print("="*60)

    num_classes = len(train_dataset.classes)
    model = SimpleCNN(num_classes=num_classes).to(device)

    total_params = sum(p.numel() for p in model.parameters())
    print(f"Total parameters: {total_params:,}")
    print(f"Model size: {total_params / 1e6:.2f}M\n")

    # Loss & Optimizer (성공한 모델과 유사하게)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=0.001)
    scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=7, gamma=0.1)

    # Early Stopping
    early_stopping = EarlyStopping(patience=7, verbose=True)

    # Training
    print("="*60)
    print("Step 4: 학습 시작")
    print("="*60)

    num_epochs = 50
    best_val_acc = 0.0

    for epoch in range(num_epochs):
        print(f"\nEpoch {epoch+1}/{num_epochs}")
        print("-" * 60)

        # Train
        train_loss, train_acc = train_epoch(model, train_loader, criterion, optimizer, device)

        # Validate
        val_loss, val_acc = validate(model, val_loader, criterion, device)

        # Scheduler
        scheduler.step()

        # Save best
        if val_acc > best_val_acc:
            best_val_acc = val_acc
            torch.save(model.state_dict(), 'best_simple_cnn.pth')

        # Print
        print(f'Train Loss: {train_loss:.4f} | Train Acc: {train_acc:.2f}%')
        print(f'Val Loss: {val_loss:.4f} | Val Acc: {val_acc:.2f}%')
        print(f'Best Val Acc: {best_val_acc:.2f}%')

        # Early Stopping
        early_stopping(val_loss, model, 'early_stop_checkpoint.pth')
        if early_stopping.early_stop:
            print(f"\nEarly Stopping at Epoch {epoch+1}")
            break

    # Test
    print("\n" + "="*60)
    print("Step 5: 최종 테스트")
    print("="*60)

    model.load_state_dict(torch.load('best_simple_cnn.pth'))
    test_loss, test_acc = validate(model, test_loader, criterion, device)

    print(f"\n최종 결과:")
    print(f"Test Accuracy: {test_acc:.2f}%")
    print(f"Best Val Accuracy: {best_val_acc:.2f}%")
    print(f"Total Parameters: {total_params:,} ({total_params/1e6:.2f}M)")
    print(f"\n학습 완료! ✅")


if __name__ == '__main__':
    main()